apiVersion: v1
kind: Service
metadata:
  name: gateway_api_service
  labels:
    name: gateway_api_service
    app: microservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
  selector:
    app: gateway_api
    type: microservice