apiVersion: v1
kind: Service
metadata:
  name: gateway-api-service
  labels:
    name: gateway-api-service
    app: microservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
  selector:
    app: gateway-api
    type: microservice