apiVersion: apps/v1
kind: Deployment
metadata:
 name: microservice_api_deploy
 labels: 
  name: microservice_api_deploy
  app: microservice
spec:
 replicas: 2
 selector: 
  matchLabels:
   app: microservice_api
   type: microservice
  template:
   metadata:
    name: microservice_api_pod
    labels:
     app: microservice_api
     type: microservice
   spec:
    containers:
    - name: microservice_app
      image: cesarrojasa/trabajointernoapi:latest
      ports:
      - containerPort: 80