apiVersion: v1
kind: Service
metadata:
 name: microservice-api-service
 labels:
  name: microservice-api-service
  app: microservice
spec:
 type: ClusterIP
 ports:
  - port: 80
    targetPort: 80
 selector:
  app: microservice-api
  type: microservice
  