apiVersion: v1
kind: Pod
metadata:
 name: microservice-api-persona-pod
 labels:
  app: microservice-api-persona
  type: microservice
spec:
 containers:
 - name: microservice-api-persona
   image: cesarrojasa/trabajointernoapipersona:latest
   ports:
   - containerPort: 80
   env: 
    - name: ConnectionStrings__MySQLTrabajoInternoAppCon
      value: Server=mysqldb-service;database=trabajointerno_mysql_db;user=root;password=0000
    - name: Services__Imagenes
      value: http://microservice-api-imagen-service
