apiVersion: v1
kind: Service
metadata:
 name: microservice-api-persona-service
 label:
  name: microservice-api-persona-service
  app: microservice
spec:
 type: ClusterIp
 ports:
  - port: 80
    targetPort: 80
 selector:
  app: microservice-persona
  type: microservice
  