apiVersion: apps/v1
kind: Deployment
metadata:
 name: microservice_api_imagen_deploy
 labels: 
  name: microservice_api_imagen_deploy
  app: microservice
spec:
 replicas: 2
 selector: 
  matchLabels:
   app: microservice_api_imagen
   type: microservice
  template:
   metadata:
    name: microservice_api_imagen_pod
    labels:
     app: microservice_api_imagen
     type: microservice
   spec:
    containers:
    - name: microservice_imagen_app
      image: cesarrojasa/trabajointernoapiimagen:latest
      ports:
       - containerPort: 80
      env: 
       - name: MongoDBTrabajoInternoSettings__Server
         value: mongodb://cesar:mongo@mongodb_service:27017