apiVersion: v1
kind: Service
metadata:
 name: microservice_api_persona_service
 app: microservice
spec:
 type: ClusterIp
 ports:
  - port: 80
    targetPort: 80
 selector:
  app: microservice_persona
  type: microservice
  