apiVersion: v1
kind: Pod
metadata:
 name: mongodb-pod
 labels:
  app: microservice-api-imagen
  name : mongodb-pod
spec:
 containers:
  - name: mongo-trabajointerno
    image: mongo:5.0
    command:
     - /bin/bash
     - -c 
    env:
     - name: MONGO_INITDB_ROOT_USERNAME
       value: "cesar"
     - name: MONGO_INITDB_ROOT_PASSWORD
       value: "0000"
    ports:
     - containerPort: 27017