apiVersion: apps/v1
kind: Deployment
metadata:
 name: mongo-deploy
 labels: 
  name: mongo-deploy
  app: microservice
spec:
 replicas: 1
 selector: 
  matchlabels:
   app: microservice_api_imagen
   name : mongo_pod
 template:
  metadata:
   name: mongodb_pod
   labels:
    app: microservice_api_imagen
    name : mongo_pod
  spec:
   containers:
   - name: mongo-trabajointerno
     image: mongo:latest
     command:
     - /bin/bash
     - -c 
     env:
     - name: MONGO_INITDB_ROOT_USERNAME
       value:  "cesar"
     - name: MONGO_INITDB_ROOT_PASSWORD
       value: "mongo"
     ports:
     - containerPort: 27017