apiVersion: v1
kind: Pod
metadata:
 name: mongodb-pod
 labels:
  app: microservice-api-imagen
  name : mongodb-pod
spec:
 containers:
  - name: mongo-trabajointerno
    image: mongo:latest
    command:
     - /bin/bash
     - -c 
    env:
     - name: MONGO_INITDB_ROOT_USERNAME
       valueFrom:
         secretKeyRef:
          name: mongo-creds
          key: cesar
     - name: MONGO_INITDB_ROOT_PASSWORD
       valueFrom:
        secretKeyRef:
          name: mongo-creds
          key: pass
    ports:
     - containerPort: 27017