apiVersion: v1
kind: Service
metadata:
 name: mongodb-service
 labels:
  name: mongodb-service
  app: database
spect: 
 type: LoadBalancer
 ports:
  - port: 27017
    targetPort: 27017
 selector: 
  app: microservice-api-imagen
  name : mongodb-pod