apiVersion: v1
kind: Pod
metadata:
 name: mongodb-pod
 labels:
  app: microservice-api-imagen
  name: mongodb-pod
spec:
 containers:
  - name: mongodb-service
    image: mongo:latest
    ports:
     - containerPort: 27017