apiVersion: v1
kind: Service
metadata:
 name: mysqldb-service
 labels:
  name: mysqldb-service
  app: database
spec: 
 type: LoadBalancer
 ports:
  - port: 27017
    targetPort: 27017
 selector: 
  app: microservice-api-persona
  name: mysqldb-pod