apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysqldb-deploy
 labels: 
  name: mysqldb-deploy
  app: microservice-api-persona
spec:
 replicas: 1
 selector: 
  matchLabels:
   app: microservice-api-persona
   name : mysqldb-pod
 template:
  metadata:
   name: mysqldb-pod
   labels:
    app: microservice-api-persona
    name: mysqldb-pod
  spec:
   containers:
    - name: mysqldb-trabajointerno
      image: mysql:latest
      ports:
       - containerPort: 3306
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: 0000