// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabajoInterno_Api_Persona.Data;

#nullable disable

namespace TrabajoInterno_Api_Persona.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    partial class MySqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TrabajoInterno_Api_Persona.Model.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_persona")
                        .HasComment("Id persona");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("apellido")
                        .HasComment("Apellidos persona");

                    b.Property<string>("CiudadNacimiento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("ciudad_Nacimiento")
                        .HasComment("Ciudad de nacimiento persona");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("correo")
                        .HasComment("Correo");

                    b.Property<int>("Edad")
                        .HasColumnType("int")
                        .HasColumnName("edad")
                        .HasComment("Edad persona");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("identificacion")
                        .HasComment("Identificacion persona");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre")
                        .HasComment("Nombre persona");

                    b.HasKey("IdPersona");

                    b.ToTable("persona", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
